Repository hobbify-team/hobbify-api, pull requests merged in 2020-07, with the labels that each got.

#17 #004 user api
  README.md
  config/settings/base.py
  config/settings/production.py
  config/urls.py
  hobbify/taskapp/tasks.py
  hobbify/templates/emails/users/account_verification.html
  hobbify/users/__init__.py
  hobbify/users/admin.py
  hobbify/users/apps.py
  hobbify/users/migrations/0001_initial.py
  hobbify/users/migrations/__init__.py
  hobbify/users/models/__init__.py
  hobbify/users/models/profiles.py
  hobbify/users/models/users.py
  hobbify/users/permissions.py
  hobbify/users/serializers/__init__.py
  hobbify/users/serializers/profiles.py
  hobbify/users/serializers/users.py
  hobbify/users/urls.py
  hobbify/users/views/__init__.py
  hobbify/users/views/users.py
  hobbify/utils/__init__.py
  hobbify/utils/models.py
  requirements/base.txt
Labels: P1

#18 #005 habits api
  config/settings/base.py
  config/urls.py
  hobbify/habits/__init__.py
  hobbify/habits/admin.py
  hobbify/habits/apps.py
  hobbify/habits/migrations/0001_initial.py
  hobbify/habits/migrations/__init__.py
  hobbify/habits/models/__init__.py
  hobbify/habits/models/habits.py
  hobbify/habits/serializers/__init__.py
  hobbify/habits/serializers/habits.py
  hobbify/habits/urls.py
  hobbify/habits/views/__init__.py
  hobbify/habits/views/habits.py
Labels: P1

#23 Fix verification link
  hobbify/templates/emails/users/account_verification.html
Labels: P1, enhancement

#26 012 recurrences
  config/settings/base.py
  config/urls.py
  hobbify/habits/migrations/0002_auto_20200707_0308.py
  hobbify/habits/migrations/0003_delete_recurrentinstance.py
  hobbify/habits/models/habits.py
  hobbify/habits/serializers/habits.py
  hobbify/recurrences/__init__.py
  hobbify/recurrences/admin.py
  hobbify/recurrences/apps.py
  hobbify/recurrences/migrations/0001_initial.py
  hobbify/recurrences/migrations/0002_auto_20200707_1847.py
  hobbify/recurrences/migrations/0003_auto_20200707_1854.py
  hobbify/recurrences/migrations/0004_auto_20200707_1855.py
  hobbify/recurrences/migrations/__init__.py
  hobbify/recurrences/models/__init__.py
  hobbify/recurrences/models/recurrent_instances.py
  hobbify/recurrences/urls.py
  hobbify/recurrences/views/__init__.py
  hobbify/recurrences/views/recurrences.py
  requirements/base.txt
Labels: P1, P2, enhancement

#30 015 add cors
  config/settings/base.py
  requirements/base.txt
Labels: P1, bug, enhancement

#28 #014 Update read me to match requirements
  README.md
Labels: P1, documentation

#32 016 fix null date
  hobbify/habits/serializers/habits.py
  hobbify/habits/views/habits.py
  hobbify/recurrences/views/recurrences.py
Labels: P1, bug

#34 Add cors origin config
  config/settings/base.py
Labels: P1, bug

#36 Disabled Caddy and Fix port to django
  config/settings/production.py
  production.yml
Labels: bug

#37 019 Add recurrences in habits
  config/settings/base.py
  config/urls.py
  hobbify/habits/migrations/0004_recurrentinstance.py
  hobbify/habits/models/__init__.py
  hobbify/habits/models/recurrent_instances.py
  hobbify/habits/serializers/__init__.py
  hobbify/habits/serializers/recurrences.py
  hobbify/habits/urls.py
  hobbify/habits/views/habits.py
  hobbify/habits/views/recurrences.py
  hobbify/recurrences/__init__.py
  hobbify/recurrences/admin.py
  hobbify/recurrences/apps.py
  hobbify/recurrences/migrations/0002_auto_20200707_1847.py
  hobbify/recurrences/migrations/0003_auto_20200707_1854.py
  hobbify/recurrences/migrations/0004_auto_20200707_1855.py
  hobbify/recurrences/migrations/__init__.py
  hobbify/recurrences/models/__init__.py
  hobbify/recurrences/urls.py
  hobbify/recurrences/views/__init__.py
  hobbify/recurrences/views/recurrences.py
Labels: P1, bug, enhancement

#38 Remove email verification
  hobbify/users/migrations/0002_auto_20200713_0249.py
  hobbify/users/models/users.py
  hobbify/users/serializers/users.py
Labels: P1
